# Generated by Django 5.0.1 on 2024-02-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task_model',
        ),
    ]
