# Generated by Django 5.0.1 on 2024-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0002_remove_category_task_model'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='category',
            field=models.ManyToManyField(to='TaskCategory.category'),
        ),
    ]
